title: Building, Brewing and Brooding
subtitle: Grab something high proof and lets jump in
email: robert.sivilli@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Hodgepodge of tech tutorials, brewing and assorted other postings.
 
url: "https://rsivilli.github.io/blog" # the base hostname & protocol for your site, e.g. http://example.com
twitter:
  username: robertsivilli
name: Robert Sivilli
locale: "en-US"
repository: rsivilli/blog
teaser: /assets/images/jekyll-og.png
#TODO find and add logo
#logo: ""
# Build settings
#theme: minimal-mistakes-jekyll
minimal_mistakes_skin: air
search: true
social:
  type: Person
  links:
    - https://www.linkedin.com/in/free-the-data/
    - https://twitter.com/RobertSivilli
    - https://github.com/rsivilli

footer:
  links:
    - label: Twitter
      icon: fab fa-fw fa-twitter-square
      url: https://twitter.com/RobertSivilli
    - label: Linkedin
      url:  https://www.linkedin.com/in/free-the-data/
      icon: fab fa-fw fa-linkedin
    - label: GitHub
      url: https://github.com/rsivilli
      icon: fab fa-fw fa-github     


plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache

remote_theme: mmistakes/minimal-mistakes


include: 
  - "_pages"
  - "_data"


defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
      author: Robert Sivilli
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      author: Robert Sivilli



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
